---
author:
  email: 
  name: An Author
  twitter: 
  url: 
baseurl: "/TestingTags2"
collections:
  annotations:
    output: true
    permalink: "/annotations/:path/"
  volume_pages:
    output: true
    permalink: "/pages/:path/"
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://loris.library.emory.edu/fedora:emory:gnfvk/full/full/0/default.jpg
image_size:
  page:
    width: 1875
    height: 1349
permalink: pretty
publication_info:
  title: Black Jacob," a monument of grace the life of Jacob Hodges, an African Negro,
    who died in Canandaigua, N.Y., February 1842 /
  date: '2020'
  editors: []
show_annotation_author: true
source_info:
  title: Black Jacob," a monument of grace the life of Jacob Hodges, an African Negro,
    who died in Canandaigua, N.Y., February 1842 /
  via_readux: true
tagline: an annotated digital edition
title: Black Jacob," a monument of grace the life of Jacob Hodges, an African Negro,
  who died in Canandaigua, N.Y., February 1842 /
url: https://jcmundy.github.io
version: 0.7
